/* eslint-disable @typescript-eslint/no-misused-promises */
import { type SignedInAuthObject } from "@clerk/nextjs/server";
import {
  type GetStaticPropsContext,
  type GetStaticPaths,
  type InferGetStaticPropsType,
} from "next";
import { ssgHelper } from "~/server/api/ssgHelper";
import { type JwtPayload, type ServerGetTokenOptions } from "@clerk/types";
import Head from "next/head";
import { type MyPage } from "~/components/types/types";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";

import { api } from "~/utils/api";
import { useUser } from "@clerk/nextjs";
import BudgetsForm from "~/components/budgets/BudgetsForm";
import CommentsForm from "~/components/comments/CommentForm";
import CommentsServiceRequest from "~/components/comments/CommentsServiceRequest";

import dynamic from "next/dynamic";
import Spinner from "~/components/ui/spinner";
import { Badge } from "~/components/ui/badge";
import { formatStatusToSpanish } from "~/helpers/status";

const budgetTableDynamic = () =>
  dynamic(() => import(`~/components/budgets/BudgetsTable`), {
    loading: () => <Spinner className="h-12 w-12 text-solBlue" />,
  });

const CategoryPage: MyPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  id,
}) => {
  const { user } = useUser();
  const request = api.serviceRequest.findById.useQuery(
    { id },
    {
      staleTime: Infinity,
    }
  );
  const { data: serviceRequest, status } = request;

  const DynamicBudgetTable = budgetTableDynamic();

  const { data: budgets, isLoading: budgetsIsLoading } =
    api.budget.getAll.useQuery(
      { serviceRequestId: id },
      {
        staleTime: Infinity,
      }
    );

  const { data: budgetListSolucionador } = api.budget.findByRequestId.useQuery(
    { serviceRequestId: id },
    {
      enabled: Boolean(user && user?.id !== serviceRequest?.userId),
    }
  );
  const rex = /([A-Z])([A-Z])([a-z])|([a-z])([A-Z])/g;

  if (!serviceRequest) {
    return (
      <>
        <Head>
          <title>Información del Servicio</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {status === "error" ? (
          <div className="flex flex-col items-center justify-center">
            <h2 className="text-2xl font-bold tracking-tight text-red-500">
              Algo salió mal
            </h2>
            <p className="text-lg text-gray-800">
              Por favor intente de nuevo, más tarde.
            </p>
          </div>
        ) : (
          <div className="flex items-center justify-center">
            <Spinner className="h-12 w-12" />
          </div>
        )}
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Contacto</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex w-full max-w-7xl flex-col items-center justify-center gap-8 px-4 py-16 ">
        <div className="w-full space-y-4 border bg-white  p-4 text-xl  font-semibold shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h1 className="text-4xl font-extrabold tracking-tight text-solBlue">
              Información de Solicitud
            </h1>
            <div>
              <Badge
                className="bg-solYellow text-black hover:bg-solYellow"
                variant="secondary"
              >
                {serviceRequest.category.name}
              </Badge>
            </div>
          </div>
          <div className="flex w-full flex-col flex-wrap gap-2">
            <div className="flex flex-wrap justify-between">
              <p className="text-lg text-gray-500">
                Estado:
                <span className="ml-1 text-sm font-bold text-sol_lightBlue">
                  {formatStatusToSpanish(serviceRequest.status)}
                </span>
              </p>
              <p className="  text-lg text-gray-500">
                Visita:
                <span className="ml-1 text-sm font-bold text-sol_lightBlue">{`${
                  serviceRequest.city ?? "-"
                }, ${serviceRequest.schedule ?? ""}.`}</span>
              </p>
              <p className="  text-lg text-gray-500">
                Dirección:
                <span className="ml-1 text-sm font-bold text-sol_lightBlue">{`${
                  serviceRequest.address ?? "-"
                }.`}</span>
              </p>
              <p className="  text-lg text-gray-500">
                Monto:
                <span className="ml-1 text-sm font-bold text-sol_lightBlue">{`${
                  serviceRequest.amount ?? "-"
                }.`}</span>
              </p>
            </div>
            <div className="flex flex-wrap justify-between">
              <p className="  text-lg text-gray-500">
                Urgencia:
                <span className="ml-1 text-sm font-bold text-sol_lightBlue">{`${
                  serviceRequest.urgency ?? "-"
                }.`}</span>
              </p>
            </div>
          </div>
          {serviceRequest?.details &&
            Object.keys(serviceRequest?.details).map((key: string, i) => (
              <p key={i}>
                <span> {key.replace(rex, "$1$4 $2$3$5")}</span>
                <span>
                  {serviceRequest?.details &&
                    serviceRequest?.details[
                      key as keyof typeof serviceRequest.details
                    ]}
                </span>
              </p>
            ))}
        </div>
        <Tabs defaultValue="account" className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="account">Presupuestos</TabsTrigger>
            <TabsTrigger value="password">Comentarios</TabsTrigger>
          </TabsList>
          <TabsContent value="account">
            <Card>
              <CardHeader>
                <CardTitle>Presupuestos</CardTitle>
                <CardDescription>aca van los presupuestos</CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
                <div className="space-y-1">
                  {/* <Budgets /> */}
                  {budgetListSolucionador && serviceRequest && (
                    <DynamicBudgetTable
                      budgets={budgetListSolucionador}
                      status={serviceRequest?.status}
                      isSolucionador={true}
                    />
                  )}
                  {user?.id !== serviceRequest?.userId &&
                    serviceRequest?.status !== "ACEPTED" && (
                      <BudgetsForm
                        serviceRequest={serviceRequest}
                        serviceRequestId={id}
                      />
                    )}

                  {user?.id === serviceRequest?.userId &&
                    !budgetsIsLoading &&
                    budgets &&
                    serviceRequest && (
                      <DynamicBudgetTable
                        budgets={budgets}
                        status={serviceRequest?.status}
                      />
                    )}
                </div>
              </CardContent>
              <CardFooter>{/* <Button>ver mas</Button> */}</CardFooter>
            </Card>
          </TabsContent>
          <TabsContent value="password">
            <Card>
              <CardHeader>
                <CardTitle>Comentarios</CardTitle>
                <CardDescription>aca van los comentarios</CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
                <div className="space-y-1">
                  {serviceRequest?.status !== "ACEPTED" && (
                    <CommentsForm
                      serviceRequest={serviceRequest}
                      serviceRequestId={id}
                      categoryName={serviceRequest?.category.name}
                    />
                  )}
                  <CommentsServiceRequest serviceRequestId={id} />
                </div>
              </CardContent>
              <CardFooter>
                <Button>Ver Más</Button>
              </CardFooter>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </>
  );
};

export default CategoryPage;
CategoryPage.Layout = "Main";

export const getStaticPaths: GetStaticPaths = () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export async function getStaticProps(
  context: GetStaticPropsContext<{ id: string }>
) {
  const id = context?.params?.id;

  if (id == null) {
    return {
      redirect: {
        destination: "/404",
      },
    };
  }
  const auth: SignedInAuthObject = {
    sessionId: "123",
    session: undefined,
    actor: undefined,
    userId: "123",
    user: undefined,
    orgId: undefined,
    orgRole: undefined,
    orgSlug: undefined,
    sessionClaims: {} as JwtPayload,
    organization: undefined,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    getToken: function (
      _options?: ServerGetTokenOptions | undefined
    ): Promise<string | null> {
      throw new Error("Function not implemented.");
    },
    debug: function (): unknown {
      throw new Error("Function not implemented.");
    },
  };
  const ssg = ssgHelper(auth);
  await ssg.serviceRequest.findById.prefetch({ id });
  await ssg.comment.getNumberOfCommentsRequest.prefetch({
    serviceRequestId: id,
  });
  return {
    props: {
      trpcState: ssg.dehydrate(),
      id,
    },
  };
}
