/* eslint-disable @typescript-eslint/no-misused-promises */
import { type SignedInAuthObject } from "@clerk/nextjs/server";
import {
  type GetStaticPropsContext,
  type GetStaticPaths,
  type InferGetStaticPropsType,
} from "next";
import { ssgHelper } from "~/server/api/ssgHelper";
import { type JwtPayload, type ServerGetTokenOptions } from "@clerk/types";
import Head from "next/head";
import { type MyPage } from "~/components/types/types";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { api } from "~/utils/api";
import ServiceComents from "~/components/servicesComponents/ServiceComents";
import CommentServiceForm from "~/components/servicesComponents/CommentServiceForm";
import { Badge } from "~/components/ui/badge";
import { AvatarSolucionador } from "~/components/ui/avatarSolucionador";
import { ConfirmServiceFinishedDialog } from "~/components/servicesComponents/confirmServiceFinishedDialog";
import Spinner from "~/components/ui/spinner";
import { ServiceReviewModal } from "~/components/servicesComponents/ServiceReviewModal";
import { useState } from "react";
import { getDateAsTwitterFormat } from "~/helpers/date";
import { format } from "date-fns";
import { formatStatusToSpanish } from "~/helpers/status";

const ServicePage: MyPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  id,
}) => {
  const request = api.service.findById.useQuery({ id });
  const { data: service, refetch } = request;
  const [open, setOpen] = useState<boolean>(false);
  if (!service) {
    return (
      <>
        <Head>
          <title>Contacto</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
          <div className="flex h-full w-full items-center justify-center">
            <Spinner className="h-24 w-24 text-solBlue" />
          </div>
        </Head>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Información del Servicio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex w-full  max-w-7xl flex-col items-center justify-center gap-8 px-4 py-16">
        <div className="w-full max-w-7xl">
          {" "}
          <div className="w-full space-y-2 py-5 text-xl font-semibold shadow-none">
            <div className="flex w-full flex-wrap items-center justify-between gap-2">
              <h1 className="text-4xl font-extrabold tracking-tight text-gray-800">
                Información del Servicio
              </h1>
              <div>
                <Badge
                  className="bg-sol_lightBlue text-white hover:bg-sol_lightBlue"
                  variant="secondary"
                >
                  {service.category.name}
                </Badge>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <div className="flex flex-wrap items-center gap-1">
                <h2 className="text-lg text-gray-500 ">Costo:</h2>
                <p className="text-sm font-bold text-solBlue">
                  ${service.budget.price}
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-1">
                <h2 className="text-lg text-gray-500 ">Fecha de Solicitud:</h2>
                <p className="text-sm font-bold text-solBlue">
                  {format(service.createdAt, "dd/MM/yyyy")}
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-1">
                <h2 className="text-lg text-gray-500 ">Estado de Solicitud:</h2>
                <p className="text-sm font-bold text-solBlue">
                  {formatStatusToSpanish(service.status)}
                </p>
              </div>

              <div className="text-sm text-gray-600">{service.description}</div>
            </div>
          </div>
          <Tabs defaultValue="comments" className="w-full ">
            <TabsList className="w-full">
              <TabsTrigger value="comments" className="w-full">
                Comentarios y Reseñas
              </TabsTrigger>
            </TabsList>

            <TabsContent value="comments">
              <Card className="bg-slate-100">
                <CardHeader className="rounded-t-lg bg-white">
                  <CardTitle className="flex items-center gap-2">
                    <AvatarSolucionador
                      userId={service.budget.author.id}
                      image={(service.budget.author.image_url as string) ?? ""}
                    />
                    <h2>Mensajes</h2>
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-2 p-0">
                  <div className="space-y-4">
                    <ServiceComents serviceId={id} />
                  </div>
                </CardContent>
                <CardFooter className="flex flex-col space-y-4 rounded-b-lg border-t-gray-300 bg-white py-4">
                  <div className="">
                    {service.status === "FINISHED" ? (
                      <ServiceReviewModal open={open} setOpen={setOpen} />
                    ) : (
                      <>
                        <CommentServiceForm
                          service={service}
                          serviceId={id}
                          categoryName={service.category.name}
                        />
                        <ConfirmServiceFinishedDialog
                          serviceId={id}
                          refetch={refetch}
                          setOpen={setOpen}
                        />
                      </>
                    )}
                  </div>
                </CardFooter>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </>
  );
};

export default ServicePage;
ServicePage.Layout = "Main";

export const getStaticPaths: GetStaticPaths = () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export async function getStaticProps(
  context: GetStaticPropsContext<{ id: string }>
) {
  const id = context?.params?.id;

  if (id == null) {
    return {
      redirect: {
        destination: "/404",
      },
    };
  }
  const auth: SignedInAuthObject = {
    sessionId: "123",
    session: undefined,
    actor: undefined,
    userId: "123",
    user: undefined,
    orgId: undefined,
    orgRole: undefined,
    orgSlug: undefined,
    sessionClaims: {} as JwtPayload,
    organization: undefined,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    getToken: function (
      _options?: ServerGetTokenOptions | undefined
    ): Promise<string | null> {
      throw new Error("Function not implemented.");
    },
    debug: function (): unknown {
      throw new Error("Function not implemented.");
    },
  };
  const ssg = ssgHelper(auth);
  await ssg.service.findById.prefetch({ id });
  return {
    props: {
      trpcState: ssg.dehydrate(),
      id,
    },
  };
}
